Feat/user page
Team-Found/bsmhub pull request #4
Opened 2024-11-25 13:17 UTC by GAMZAMANDU

## 💡 개요
1. user-page의 Tab 간 섹션 전환을 완성했습니다.
2. posts를 제외한 user-page창의 퍼블리싱을 완료했습니다.

## 📃 작업내용
- tab이 home일때 화면 제작.
- tab이 projects일때 화면 (전체, 개인, 협업)으로 나뉨.

## 🔀 변경사항
- user-pages의 변경부분을 컴포넌트화했습니다.

## 📸 스크린샷
<img width="1680" alt="스크린샷 2024-11-25 오후 10 16 31" src="https://github.com/user-attachments/assets/648c47c6-37f6-4967-92c6-ec0c8c5b230d">
<img width="1680" alt="스크린샷 2024-11-25 오후 10 16 46" src="https://github.com/user-attachments/assets/a41bd39a-cd12-486f-bc82-e6f2ea780b2d">

2024-11-25 13:51 UTC, jaehwan02 requested changes
### 프로젝트 상하 gap이 너무 좁아요
---
![image](https://github.com/user-attachments/assets/2c233521-c7e5-4af5-8c6b-a8d3a752af62)

### user 접속시 생기는 오류 (useEffect 미사용)
---
<img width="525" alt="image" src="https://github.com/user-attachments/assets/101d9425-d21a-4f73-b663-f7b87fc07cfd">

### next/head가 아닌 Metadata API를 사용할 필요가 있음
---
<img width="674" alt="image" src="https://github.com/user-attachments/assets/3f2cd375-8e1a-4b5c-ba8f-d50701364fc6">
<img width="609" alt="image" src="https://github.com/user-attachments/assets/a927a0bc-c8d7-4e4f-81b9-cc379f34f65c">

2024-11-25 14:04 UTC, obtuse-triangle requested changes

2024-11-25 14:04 UTC, obtuse-triangle commented on src/app/components/detail/DetailBox.tsx
> +		<div className="block w-[21.0625rem] overflow-auto min-h-[9rem] h-auto p-14px mb-[1.2rem] border border-strokeColor rounded-lg">
min-w, max-w와 w-[30%]로 반응형 설계하기 [태블릿 등 데스크톱보다 작은 너비]

2024-11-25 14:04 UTC, obtuse-triangle commented on src/app/components/ProjectItem.tsx
> +      <div className="w-[21.0625rem] h-[11.8125rem] bg-[#F1F1F1] rounded-2xl overflow-hidden">
min-w, max-w와 w-[30%]로 반응형 설계하기 [태블릿 등 데스크톱보다 작은 너비] 22
height 소수점 절삭하기

2024-11-25 14:04 UTC, obtuse-triangle commented on src/app/components/section/UserHome.tsx
> +				<ProjectItem tag="개발완료" category="Desktop Utility" title="SANDDOET-App" description="산뜻 - AI 추천 RSS로 정보 습득이 쉬워지는 순간!" />
interface 타입 만들어서 map으로 출력하게 하기

2024-11-25 14:04 UTC, obtuse-triangle commented on tsconfig.json
> +      "@public/*": ["./public/*"],
👍

2024-11-25 14:10 UTC, obtuse-triangle commented
This pull request introduces several new components and updates to the `src/app/components` directory to enhance the user interface and functionality. The changes include the addition of new components for displaying project items, user home sections, user posts, and user projects, as well as updates to existing components to improve layout and responsiveness.

New components:

* [`src/app/components/ProjectItem.tsx`](diffhunk://#diff-08de2d869f4ef04fe67ca9e11fc7fa44668d56ea879241f22da79f0c77173a37R1-R46): Added a new `ProjectItem` component to display individual project details, including an image, tag, category, title, and description.
* [`src/app/components/section/UserHome.tsx`](diffhunk://#diff-6279e34a16b01996b716e47bd52b7085486f4012ca1335fce320e5004d0a11e4R1-R21): Created a new `UserHome` component that includes a section for markdown input, detail boxes, and a list of personal projects using the `ProjectItem` component.
* [`src/app/components/section/UserPosts.tsx`](diffhunk://#diff-521b791d62556ddb102c2c3871e779b2fc0ce8ff1bcd5f64aac98f2a044c0449R1-R9): Added a new `UserPosts` component as a placeholder for user posts.
* [`src/app/components/section/UserProjects.tsx`](diffhunk://#diff-3c03749696f5467b6b6a07385e5b2f79eef9015c8c47cf6e429aa0a9d5f8048cR1-R31): Introduced a new `UserProjects` component with tabs for different project categories and a list of project items.
* [`src/app/components/section/UserTabs.tsx`](diffhunk://#diff-39700455215d7ee932660e3d8aae37706a7007b998610cbdb8c7e60d60df54a4R1-R26): Implemented a new `UserTabs` component to handle tab navigation between home, projects, and posts sections using URL parameters.

Updates to existing components:

* [`src/app/components/detail/DetailBox.tsx`](diffhunk://#diff-39224e0e17e7a411daa6b4d9cd84c4633e44117caeb1891189ae83708c39fb13L18-R18): Adjusted the width of the `DetailBox` component to improve layout consistency.
* [`src/app/components/detail/DetailBoxes.tsx`](diffhunk://#diff-39f6d94b035515bb22f2cf889b224f7e7ac9ab6e06ca6858b774e84050a60c25L7-R7): Modified the `DetailBoxes` component to use a flexible layout with wrapping and adjusted gaps between items.
* [`src/app/user/template.tsx`](diffhunk://#diff-83594f342ec877fc4aba22f0a069c283a5be81748fbd140ef5cfe763a3437a49L4-R4): Updated the `UserTemplate` component to replace the markdown section and detail boxes with the new `UserTabs` component for improved navigation and organization. [[1]](diffhunk://#diff-83594f342ec877fc4aba22f0a069c283a5be81748fbd140ef5cfe763a3437a49L4-R4) [[2]](diffhunk://#diff-83594f342ec877fc4aba22f0a069c283a5be81748fbd140ef5cfe763a3437a49L32-R34)

2024-11-25 18:22 UTC, obtuse-triangle commented
// TODO: Detail.tsx의 'use client'제거

2024-11-28 07:41 UTC, jaehwan02 approved these changes

2024-11-28 07:46 UTC, obtuse-triangle approved these changes

2024-11-28 08:00 UTC, obtuse-triangle commented on src/app/components/detail/DetailBox.tsx
> +		<div className="block w-[21.0625rem] overflow-auto min-h-[9rem] h-auto p-14px mb-[1.2rem] border border-strokeColor rounded-lg">
#5 로 이동

2024-11-28 08:00 UTC, obtuse-triangle commented on src/app/components/ProjectItem.tsx
> +      <div className="w-[21.0625rem] h-[11.8125rem] bg-[#F1F1F1] rounded-2xl overflow-hidden">
#5 로 이동

2024-11-28 08:00 UTC, merged