Feat/contest page
Team-Found/bsmhub pull request #6
Opened 2024-11-28 08:13 UTC by jaehwan02

## 💡 개요
대회 컴포넌트를 생성하였습니다.

## 📃 작업내용

* [`src/app/components/layout/ContestItem.tsx`](diffhunk://#diff-13807d1da876345320199cf3f63e6a62f1465533f53f1dfce185c7b470388edfR1-R23): `ContestItem` 컴포넌트 생성

* [`src/app/contest/page.tsx`](diffhunk://#diff-4517c130070ef31782689b7db72f2b6aba56c69ac14b898ea74db8080e5c6cd6R1-R48): `ContestPage` 페이지 생성

## 📸 스크린샷

<img width="1174" alt="image" src="https://github.com/user-attachments/assets/18f36b1d-a77e-4dce-af46-1b7af3f1a632">

2024-11-28 12:05 UTC, obtuse-triangle requested changes

2024-11-28 12:05 UTC, obtuse-triangle commented on src/app/contest/layout.tsx
> +			<div className="mx-auto bg-white w-full h-[calc(100dvh-7rem)] text-black max-w-outer">{children}</div>
hight를 고정하면 스크롤이 부자연스러워질거 같은데

2024-11-28 12:05 UTC, obtuse-triangle commented on src/app/contest/layout.tsx
> +		<div className="z-[-1]">
Z-Index는 왜 필요한건지 설명좀

2024-11-28 12:06 UTC, obtuse-triangle commented on src/app/contest/layout.tsx
> +			<div className="mx-auto bg-white w-full h-[calc(100dvh-7rem)] text-black max-w-outer">{children}</div>
`h-[calc(100dvh-7rem)]`

2024-11-28 12:14 UTC, GAMZAMANDU approved these changes

2024-12-03 07:43 UTC, obtuse-triangle approved these changes

2024-12-03 07:47 UTC, merged